### ISSUE TITLE
Peruvian purple potatoes

### ISSUE THREAD

**Issue by d-mansupport** [Rhys-Grover/French-Fri-Clicker#1]
![download](https://user-images.githubusercontent.com/83715408/117178775-63764500-ada0-11eb-8914-a9e9cf89637b.jpg)
So, the idea is purple potatoes, (Aka Thanos potatoes) possibly as an early game item OR ability. the ability would increase all potato fps by 5% (Possibly more)

**Comment by Smunk3y** [comment]
Will Look Into It
