### ISSUE TITLE
New tab issue

### ISSUE THREAD

**Issue by d-mansupport** [Rhys-Grover/French-Fri-Clicker#2]
![Screenshot 2021-05-06 112615](https://user-images.githubusercontent.com/83715408/117324593-f0330880-ae5d-11eb-9c64-9a9b8330fdba.png)
Not really a bug however when you don't have enough fries to buy something it opens a new tab. bug? no. mistake? maybe.

**Comment by Smunk3y** [comment]
Resolved in latest Relase
